version: '3.8'
services:
  neo4j:
    image: neo4j:5.18.1
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - .docker/neo4j/data:/data
    environment:
      NEO4J_AUTH: neo4j/localhost
